# Config file for aws empty-test functions 
#
service: aws-empty-test-functions-nodejs

provider:
  name: aws
  memorySize: 128
  timeout: 6
  stage: ${opt:stage,'dev'}
  region: ${opt:region,'us-east-1'}
  versionFunctions: true # Optional function versioning

custom:
  # you can use rate() or cron() syntax
  warmStartInterval: cron(56/1 * * * ? *) # every 1 minute starting at 56 past the hour => 4 per hour (but 1st will likely be cold)

# individual function definitions
functions:
  aws-warm-empty-nodejs12x:
    runtime: nodejs12.x
    handler: ./handler.emptytestnodejs
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-nodejs12x-${self:provider.stage}-minute
          enabled: false   
  aws-warm-256-empty-nodejs12x:
    runtime: nodejs12.x
    handler: ./handler.emptytestnodejs
    memorySize: 256
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-256-nodejs12x-${self:provider.stage}-minute
          enabled: false
  aws-warm-512-empty-nodejs12x:
    runtime: nodejs12.x
    handler: ./handler.emptytestnodejs
    memorySize: 512
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-512-nodejs12x-${self:provider.stage}-minute
          enabled: false   

  aws-warm-empty-nodejs10x:
    runtime: nodejs10.x
    handler: ./handler.emptytestnodejs
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-nodejs10x-${self:provider.stage}-minute
          enabled: false   
  aws-warm-256-empty-nodejs10x:
    runtime: nodejs10.x
    handler: ./handler.emptytestnodejs
    memorySize: 256
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-256-nodejs10x-${self:provider.stage}-minute
          enabled: false
  aws-warm-512-empty-nodejs10x:
    runtime: nodejs10.x
    handler: ./handler.emptytestnodejs
    memorySize: 512
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-512-nodejs10x-${self:provider.stage}-minute
          enabled: false                               

  # begin cold-start test functions. 
  # No events - they're triggered by the batch cold start schedulers below.      
  aws-cold-empty-nodejs12x:
    runtime: nodejs12.x
    handler: ./handler.emptytestnodejs
  aws-cold-256-empty-nodejs12x:
    runtime: nodejs12.x
    handler: ./handler.emptytestnodejs
    memorySize: 256
  aws-cold-512-empty-nodejs12x:
    runtime: nodejs12.x
    handler: ./handler.emptytestnodejs
    memorySize: 512

  aws-cold-empty-nodejs10x:
    runtime: nodejs10.x
    handler: ./handler.emptytestnodejs
  aws-cold-256-empty-nodejs10x:
    runtime: nodejs10.x
    handler: ./handler.emptytestnodejs
    memorySize: 256
  aws-cold-512-empty-nodejs10x:
    runtime: nodejs10.x
    handler: ./handler.emptytestnodejs
    memorySize: 512    


