# Config file for empty-test .net core 2.0 function
#
# For full config options, check the docs:
#    docs.serverless.com
#

service: awsservicedotnet2

provider:
  name: aws
  runtime: dotnetcore2.0
  memorySize: 128
  timeout: 6
  stage: dev
  region: us-east-1

# you can add packaging information here
package:
  artifact: bin/release/netcoreapp2.0/deploy-package.zip

functions:
  awsdotnet2:
    handler: CsharpHandlers::ServerlessPerformanceFramework.Handler::EmptyTestDotNetCore2
    events:
      - schedule: 
          rate: rate(1 hour)
          name: coldstart-dotnet2-hourly
          enabled: false
      - schedule: 
          rate: rate(1 minute)
          name: warmstart-dotnet2-minute
          enabled: false

