# Serverless Performance Test Framework
# Config file for Lambda Service to store provided lambda metrics data into Dynamo DB
service: spf-api

custom:
  environmentConfiguration:
    dev:
      dynamoDeletionPolicy: Retain
      dynamoReadCapacityUnits: 2
      dynamoWriteCapacityUnits: 2
      dynamoReadTimeoutSeconds: 1
      dynamoReadRetryLimit: 1
      readAPIFunctionTimeout: 5
    prod:
      dynamoDeletionPolicy: Retain
      dynamoReadCapacityUnits: 8
      dynamoWriteCapacityUnits: 8
      dynamoReadTimeoutSeconds: 3
      dynamoReadRetryLimit: 1
      readAPIFunctionTimeout: 10

provider:
  name: aws
  memorySize: 128
  timeout: 12
  stage: ${opt:stage,'dev'}
  region: ${opt:region,'us-east-1'}
  endpointType: REGIONAL
  environment:
    AWS_LAMBDA_GBSECOND_COST: "0.00001667"
    AWS_LAMBDA_INVOKE_COST: "0.0000002"
    AZURE_FUNCTIONS_GBSECOND_COST: "0.000016"
    AZURE_FUNCTIONS_INVOKE_COST: "0.0000002"
    DYNAMODB_TABLE: "ServerlessFunctionMetrics-${self:provider.stage}"
    DYNAMODB_READ_TIMEOUT_SECONDS: ${self:custom.environmentConfiguration.${self:provider.stage}.dynamoReadTimeoutSeconds}
    DYNAMODB_READ_RETRY_ATTEMPT_LIMIT: ${self:custom.environmentConfiguration.${self:provider.stage}.dynamoReadRetryLimit}

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*/index/*"


# packaging information here
functions:
  get-summary-stats:
      handler: getruntime/summarystats.getSummaryStats
      runtime: python3.8
      memorySize: 256
      timeout: ${self:custom.environmentConfiguration.${self:provider.stage}.readAPIFunctionTimeout}
      events:
        - http:
            path:  runtimes/{runtimeId}/summary
            method: get
            cors:
              origin: ${opt:corsorigin,'*'}
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - X-Amz-User-Agent
              allowCredentials: false
            request:
              parameters:
                querystrings:
                  platform: false
                  state: false
                  memory: false
                  type: false
                  startDate: false
                  endDate: false
                  region: false
                paths:
                  runtimeId: true  
  get-mean:
    handler: getruntime/mean.getMeanDuration
    runtime: python3.8
    timeout: ${self:custom.environmentConfiguration.${self:provider.stage}.readAPIFunctionTimeout}
    events:
      - http:
          path:  runtimes/{runtimeId}/mean
          method: get
          cors:
            origin: ${opt:corsorigin,'*'}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          request:
            parameters:
              querystrings:
                platform: false
                state: false
                memory: false
                type: false
                startDate: false
                endDate: false
                region: false
              paths:
                runtimeId: true
  get-runtime-min:
    handler: getruntime/maxmin.getMinimum
    runtime: python3.8
    timeout: ${self:custom.environmentConfiguration.${self:provider.stage}.readAPIFunctionTimeout}
    events:
      - http:
          path:  runtimes/{runtimeId}/minimum
          method: get
          cors:
            origin: ${opt:corsorigin,'*'}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          request:
            parameters:
              querystrings:
                platform: false
                state: false
                memory: false
                type: false
                startDate: false
                endDate: false
                region: false
              paths:
                runtimeId: true
  get-runtime-max:
    handler: getruntime/maxmin.getMaximum
    runtime: python3.8
    timeout: ${self:custom.environmentConfiguration.${self:provider.stage}.readAPIFunctionTimeout}
    events:
      - http:
          path:  runtimes/{runtimeId}/maximum
          method: get
          cors:
            origin: ${opt:corsorigin,'*'}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false          
          request:
            parameters:
              querystrings:
                platform: false
                state: false
                memory: false
                type: false
                startDate: false
                endDate: false
                region: false
              paths:
                runtimeId: true
  lambda-metrics:
    runtime: dotnetcore2.1
    timeout: 30 # max for api-backed lambdas 
    handler: CsharpHandlers::ServerlessPerformanceFramework.Handler::LambdaMetrics
    package:
      artifact: lambda-metrics-service/bin/release/netcoreapp2.1/deploy-package.zip
    events:
      - http:
          path: metrics
          method: post
    environment:
      DYNAMODB_METRICS_TABLE: "ServerlessFunctionMetrics-${self:provider.stage}"     

resources:
  Outputs:
    SpfApiUrl:
      Description: The URL for the published API
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"  
      Export:
        Name: "SpfApiUrl-${self:provider.stage}"

  Resources:
    LambdaMetricsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: ${self:custom.environmentConfiguration.${self:provider.stage}.dynamoDeletionPolicy}
      Properties:
        TableName: "ServerlessFunctionMetrics-${self:provider.stage}"
        AttributeDefinitions:
          - AttributeName: LanguageRuntime
            AttributeType: S
          - AttributeName: RequestId
            AttributeType: S   
          - AttributeName: Duration
            AttributeType: N                           
        KeySchema:
          - AttributeName: LanguageRuntime
            KeyType: HASH
          - AttributeName: RequestId
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: duration-index
            KeySchema:
              - AttributeName: LanguageRuntime
                KeyType: HASH
              - AttributeName: Duration
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.environmentConfiguration.${self:provider.stage}.dynamoReadCapacityUnits}
          WriteCapacityUnits: ${self:custom.environmentConfiguration.${self:provider.stage}.dynamoWriteCapacityUnits}
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Comment: CloudFront for SPF API
          Aliases:
            # alias must match that specified for the R53 record set (see below)
            - ${opt:domain,'api-dev.serverlessperformance.net'}
          ViewerCertificate:
            # see pre-requisites for Route53 setup (optional) in readme and update ARN here
            AcmCertificateArn: ${opt:acmcertarn,'arn:aws:acm:us-east-1:662198257344:certificate/564a004a-c993-4f05-a47d-0b7a0a09f5e8'}
            MinimumProtocolVersion: TLSv1.2_2018
            SslSupportMethod: sni-only
          DefaultCacheBehavior:
            TargetOriginId: OriginSPFAPI${self:provider.stage}
            ViewerProtocolPolicy: 'redirect-to-https'
            DefaultTTL: 31536000
            MaxTTL: 31536000
            MinTTL: 0
            ForwardedValues:
              # note by not specifying QueryStringCacheKeys, we ensure cloudfront caches based on all combined query strings which we want
              QueryString: true
          Enabled: true
          PriceClass: PriceClass_100
          Origins:
            - Id: OriginSPFAPI${self:provider.stage}
              DomainName:
                Fn::Join:
                  - ""
                  - - Ref: ApiGatewayRestApi
                    - ".execute-api.${self:provider.region}.amazonaws.com"
              CustomOriginConfig:
                OriginProtocolPolicy: https-only 
    Route53RecordSetA:
      Type: AWS::Route53::RecordSet
      Properties: 
        AliasTarget: 
          DNSName: !GetAtt CloudFrontDistribution.DomainName
          # HostedZoneId is always Z2FDTNDATAQYW2 for cloudfront
          # See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget-1.html 
          HostedZoneId: Z2FDTNDATAQYW2
        Comment: DNS for CloudFront distribution for SPF API
        HostedZoneName: ${opt:hostedzone,'serverlessperformance.net.'}
        Name: ${opt:domain,'api-dev.serverlessperformance.net'}
        Type: A   
    Route53RecordSetAAAA:
      Type: AWS::Route53::RecordSet
      Properties: 
        AliasTarget:
          DNSName: !GetAtt CloudFrontDistribution.DomainName
          # HostedZoneId is always Z2FDTNDATAQYW2 for cloudfront 
          HostedZoneId: Z2FDTNDATAQYW2 
        Comment: DNS for CloudFront distribution for SPF API
        HostedZoneName: ${opt:hostedzone,'serverlessperformance.net.'}
        Name: ${opt:domain,'api-dev.serverlessperformance.net'}
        Type: AAAA