# This function is part of the AWS performance testing framework. It is triggered from cloud-watch
# logs of any specified target functions (via their cloud watch logs) under "events:" below.

service: nodejs-perf-logger

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 20
  region: us-east-1
  stage: dev
  versionFunctions: true # Optional function versioning
  # Import the API Url that was exported from the API serverless module (TODO - add ${self:provider:stage} to the export/import )
  environment:
    POST_METRICS_URL: 
      'Fn::ImportValue': 'SpfApiUrl'

  
# packaging information here
package:
  include:
    - node_modules/**

functions:
  # logger per runtime to get around limitations on number of event triggers per function
  logger-node:
    handler: handler.logger
    events:
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-dev-aws-warm-empty-node810'
          filter: 'REPORT'   
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-dev-aws-cold-empty-node810'
          filter: 'REPORT'                  
  logger-dotnet:
    handler: handler.logger
    events:
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-dev-aws-warm-empty-dotnet21'
          filter: 'REPORT'
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-dev-aws-cold-empty-dotnet21'
          filter: 'REPORT'          
  logger-java:
    handler: handler.logger
    events:
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-dev-aws-warm-empty-java8'
          filter: 'REPORT'
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-dev-aws-cold-empty-java8'
          filter: 'REPORT'          
  logger-python:
    handler: handler.logger
    events:
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-dev-aws-warm-empty-python36'
          filter: 'REPORT'
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-dev-aws-cold-empty-python36'
          filter: 'REPORT'          
  logger-go:
    handler: handler.logger
    events:
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-dev-aws-warm-empty-go'
          filter: 'REPORT'     
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-dev-aws-cold-empty-go'
          filter: 'REPORT'                  


