# This function is part of the AWS performance testing framework. It is triggered from cloud-watch
# logs of any specified target functions (via their cloud watch logs) under "events:" below.

service: nodejs-perf-logger

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 20
  stage: ${opt:stage,'dev'}
  region: ${opt:region,'us-east-1'}
  versionFunctions: true # Optional function versioning
  # Import the API Url that was exported from the API serverless module
  environment:
    POST_METRICS_URL: 
      'Fn::ImportValue': "SpfApiUrl-${self:provider.stage}"

  
# packaging information here
package:
  include:
    - node_modules/**

functions:
  # logger per runtime to get around limitations on number of event triggers per function
  logger-node:
    handler: handler.logger
    events:
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-empty-nodejs12x'
          filter: 'REPORT'   
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-nodejs12x'
          filter: 'REPORT'                  
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-256-empty-nodejs12x'
          filter: 'REPORT'   
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-256-empty-nodejs12x'
          filter: 'REPORT'   
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-512-empty-nodejs12x'
          filter: 'REPORT'   
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-512-empty-nodejs12x'
          filter: 'REPORT'     
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-empty-nodejs10x'
          filter: 'REPORT'   
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-nodejs10x'
          filter: 'REPORT'                  
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-256-empty-nodejs10x'
          filter: 'REPORT'   
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-256-empty-nodejs10x'
          filter: 'REPORT'   
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-512-empty-nodejs10x'
          filter: 'REPORT'   
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-512-empty-nodejs10x'
          filter: 'REPORT'                                 

  logger-dotnet:
    handler: handler.logger
    events:
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-empty-dotnet21'
          filter: 'REPORT'
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-dotnet21'
          filter: 'REPORT'           
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-256-empty-dotnet21'
          filter: 'REPORT'         
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-256-empty-dotnet21'
          filter: 'REPORT'          
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-512-empty-dotnet21'
          filter: 'REPORT'         
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-512-empty-dotnet21'
          filter: 'REPORT'   

  logger-java:
    handler: handler.logger
    events:
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-empty-java8'
          filter: 'REPORT'
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-java8'
          filter: 'REPORT'          
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-256-empty-java8'
          filter: 'REPORT'
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-256-empty-java8'
          filter: 'REPORT'          
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-512-empty-java8'
          filter: 'REPORT'
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-512-empty-java8'
          filter: 'REPORT'   

  logger-python:
    handler: handler.logger
    events:
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-empty-python36'
          filter: 'REPORT'
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-python36'
          filter: 'REPORT' 
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-256-empty-python36'
          filter: 'REPORT'
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-256-empty-python36'
          filter: 'REPORT' 
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-512-empty-python36'
          filter: 'REPORT'
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-512-empty-python36'
          filter: 'REPORT' 
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-empty-python38'
          filter: 'REPORT'
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-python38'
          filter: 'REPORT' 
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-256-empty-python38'
          filter: 'REPORT'
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-256-empty-python38'
          filter: 'REPORT' 
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-512-empty-python38'
          filter: 'REPORT'
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-512-empty-python38'
          filter: 'REPORT'           

  logger-go:
    handler: handler.logger
    events:
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-empty-go'
          filter: 'REPORT'  
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-go'
          filter: 'REPORT'                  
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-256-empty-go'
          filter: 'REPORT'     
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-256-empty-go'
          filter: 'REPORT'                  
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-warm-512-empty-go'
          filter: 'REPORT'     
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-empty-test-functions-${self:provider.stage}-aws-cold-512-empty-go'
          filter: 'REPORT'  

