# This function is part of the AWS performance testing framework. It is triggered from cloud-watch
# logs of any specified target functions (via their cloud watch logs) under "events:" below.

service: nodejs-perf-logger

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 20
  region: us-east-1
  stage: dev
  versionFunctions: true # Optional function versioning

  
# packaging information here
package:
  include:
    - node_modules/**

functions:
  logger:
    handler: handler.logger
    events:
      - cloudwatchLog:
          logGroup: '/aws/lambda/awsservicenode610-dev-awsnode610'
          filter: 'REPORT'
      - cloudwatchLog:
          logGroup: '/aws/lambda/awsservicedotnet2-dev-awsdotnet2'
          filter: 'REPORT'
      - cloudwatchLog:
          logGroup: '/aws/lambda/awsservicepython3-dev-awspython3'
          filter: 'REPORT'
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-service-java8-dev-aws-empty-java8'
          filter: 'REPORT'
      - cloudwatchLog:
          logGroup: '/aws/lambda/aws-service-go-dev-aws-empty-go'
          filter: 'REPORT'

# Define function environment variables here
    environment:
      POST_METRICS_URL: ${opt:postmetricsurl}

