# Config file for Lambda Service to store provided lambda metrics data
# into Dynamo DB
#
# For full config options, check the docs:
#    docs.serverless.com
#

service: lambda-metrics-service

provider:
  name: aws
  runtime: dotnetcore2.0
  memorySize: 128
  timeout: 12 
  stage: dev
  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*/index/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  artifact: bin/release/netcoreapp2.0/deploy-package.zip

functions:
  lambdaMetrics:
    handler: CsharpHandlers::ServerlessPerformanceFramework.Handler::LambdaMetrics

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
    events:
      - http:
          path: metrics
          method: post

