# Serverless Performance Test Framework
# Cost calculations service based on provided performance data

service: lambda-cost-service

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 12

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*/index/*"


# packaging information here
package:
  include:
    - node_modules/**

functions:
  cost-metrics:
    handler: handler.costmetrics
    events:
      - sns: performance-metrics-topic

# Define function environment variables here
    environment:
      DYNAMODB_COSTMETRICS_TABLE: "ServerlessCostMetrics"
