# Config file for aws empty-test functions
#
service: aws-empty-test-functions-cold-burst

custom:
  # you can use rate() or cron() syntax
  coldStartInterval: rate(60 minutes) # minutes => 1 hour 
  coldStartBatchSize: 3 # e.g. if 3 every 60 minutes => 3 per hour
  coldStartBatchMemory: 512

provider:
  name: aws
  memorySize: ${self:custom.coldStartBatchMemory}
  timeout: 6
  stage: ${opt:stage,'dev'}
  region: ${opt:region,'us-east-1'}
  versionFunctions: true # Optional function versioning
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:${self:provider.region}:*:function:aws-empty-test*" 

coldstart-param-reuse: &coldstart-param
  runtime: python3.8
  handler: handler.burst_invoker
  memorySize: ${self:custom.coldStartBatchMemory}

functions:
  # cold-start-scheduler functions
  awsgo-coldstart:
    <<: *coldstart-param
    events:
      - schedule: 
          rate: ${self:custom.coldStartInterval}
          name: coldstart-go-${self:provider.stage}-hourly-burst
          enabled: false
          input:
            invokeCount: ${self:custom.coldStartBatchSize}
            targetFunctionName: 
              - aws-empty-test-functions-go-${self:provider.stage}-aws-cold-empty-go
              - aws-empty-test-functions-go-${self:provider.stage}-aws-cold-256-empty-go
              - aws-empty-test-functions-go-${self:provider.stage}-aws-cold-512-empty-go

  awsdotnet2-coldstart:
    <<: *coldstart-param
    events:
      - schedule: 
          rate: ${self:custom.coldStartInterval}
          name: coldstart-dotnet21-${self:provider.stage}-hourly-burst
          enabled: false
          input:
            invokeCount: ${self:custom.coldStartBatchSize}
            targetFunctionName: 
              - aws-empty-test-functions-dotnet-${self:provider.stage}-aws-cold-empty-dotnet21
              - aws-empty-test-functions-dotnet-${self:provider.stage}-aws-cold-256-empty-dotnet21
              - aws-empty-test-functions-dotnet-${self:provider.stage}-aws-cold-512-empty-dotnet21

  awsjava8-coldstart:
    <<: *coldstart-param
    events:
      - schedule: 
          rate: ${self:custom.coldStartInterval}
          name: coldstart-java8-${self:provider.stage}-hourly-burst
          enabled: false
          input:
            invokeCount: ${self:custom.coldStartBatchSize}
            targetFunctionName: 
              - aws-empty-test-functions-java-${self:provider.stage}-aws-cold-empty-java8
              - aws-empty-test-functions-java-${self:provider.stage}-aws-cold-256-empty-java8
              - aws-empty-test-functions-java-${self:provider.stage}-aws-cold-512-empty-java8

  awsnodejs12x-coldstart:
    <<: *coldstart-param
    events:
      - schedule: 
          rate: ${self:custom.coldStartInterval}
          name: coldstart-nodejs12x-${self:provider.stage}-hourly-burst
          enabled: false
          input:
            invokeCount: ${self:custom.coldStartBatchSize}
            targetFunctionName: 
              - aws-empty-test-functions-nodejs-${self:provider.stage}-aws-cold-empty-nodejs12x
              - aws-empty-test-functions-nodejs-${self:provider.stage}-aws-cold-256-empty-nodejs12x
              - aws-empty-test-functions-nodejs-${self:provider.stage}-aws-cold-512-empty-nodejs12x

  awsnodejs10x-coldstart:
    <<: *coldstart-param
    events:
      - schedule: 
          rate: ${self:custom.coldStartInterval}
          name: coldstart-nodejs10x-${self:provider.stage}-hourly-burst
          enabled: false
          input:
            invokeCount: ${self:custom.coldStartBatchSize}
            targetFunctionName: 
              - aws-empty-test-functions-nodejs-${self:provider.stage}-aws-cold-empty-nodejs10x
              - aws-empty-test-functions-nodejs-${self:provider.stage}-aws-cold-256-empty-nodejs10x
              - aws-empty-test-functions-nodejs-${self:provider.stage}-aws-cold-512-empty-nodejs10x
  
  awspython36-coldstart:
    <<: *coldstart-param
    events:
      - schedule: 
          rate: ${self:custom.coldStartInterval}
          name: coldstart-python36-${self:provider.stage}-hourly-burst
          enabled: false
          input:
            invokeCount: ${self:custom.coldStartBatchSize}
            targetFunctionName: 
              - aws-empty-test-functions-python-${self:provider.stage}-aws-cold-empty-python36
              - aws-empty-test-functions-python-${self:provider.stage}-aws-cold-256-empty-python36
              - aws-empty-test-functions-python-${self:provider.stage}-aws-cold-512-empty-python36

  awspython38-coldstart:
    <<: *coldstart-param
    events:
      - schedule: 
          rate: ${self:custom.coldStartInterval}
          name: coldstart-python38-${self:provider.stage}-hourly-burst
          enabled: false
          input:
            invokeCount: ${self:custom.coldStartBatchSize}
            targetFunctionName: 
              - aws-empty-test-functions-python-${self:provider.stage}-aws-cold-empty-python38
              - aws-empty-test-functions-python-${self:provider.stage}-aws-cold-256-empty-python38
              - aws-empty-test-functions-python-${self:provider.stage}-aws-cold-512-empty-python38

