# Logger function to take metrics and deliver them to the performance metrics framework via API call

service: azure-perf-logger

provider:
  name: azure
  location: East US

plugins:
  - serverless-azure-functions

# you can add packaging information here
package:
  include:
    - node_modules/**

functions:
  logger:
    handler: handler.logger
    events:
      - blob:
        x-azure-settings:
          name: metricsBlob
          path: nodejs-perf-metrics/{name}
          connection: ${opt:storageaccountconnectionstring}

# The following are a few examples of other events you can configure:
#
# events:
#   - queue: YourQueueName
#     x-azure-settings:
#       connection : StorageAppSettingName
#   - blob:
#     x-azure-settings:
#       name: bindingName
#       direction: in

# Define function environment variables here
#    environment:
#      POST_METRICS_URL: ${opt:postmetricsurl}
