# Config file for aws empty-test functions - all runtimes
#
service: aws-empty-test-functions

provider:
  name: aws
  memorySize: 128
  timeout: 6
  stage: dev
  region: us-east-1
  versionFunctions: true # Optional function versioning

# package (e.g. .net zip) is specified per function rather than centrally as some don't need a package
package:
  individually: true 

# individual function definitions
functions:
  dotnet2:
    runtime: dotnetcore2.1
    handler: CsharpHandlers::ServerlessPerformanceFramework.Handler::EmptyTestDotNetCore2
    package:
      artifact: aws-service-dotnetcore2/bin/release/netcoreapp2.1/deploy-package.zip
    events:
      - schedule: 
          rate: rate(1 hour)
          name: coldstart-dotnet2-hourly
          enabled: false
      - schedule: 
          rate: rate(1 minute)
          name: warmstart-dotnet2-minute
          enabled: false
  aws-empty-go:
    runtime: go1.x
    handler: aws-service-go/bin/go-empty-function
    package:
      exclude:
        - ./aws-service-go/**
      include:
        - ./aws-service-go/bin/**
    events:
      - schedule: 
          rate: rate(1 hour)
          name: coldstart-golang-hourly
          enabled: false
      - schedule: 
          rate: rate(1 minute)
          name: warmstart-golang-minute
          enabled: false
  aws-empty-java8:
    runtime: java8
    handler: com.learnspree.EmptyJava8Handler
    package:
      artifact: aws-service-java8/target/awsjava8empty-dev.jar
    events:
      - schedule: 
          rate: rate(1 hour)
          name: coldstart-java8-hourly
          enabled: false
      - schedule: 
          rate: rate(1 minute)
          name: warmstart-java8-minute
          enabled: false
  awsnode810:
    runtime: nodejs8.10
    handler: aws-service-node810/handler.emptytestnode810
    events:
      - schedule: 
          rate: rate(1 hour)
          name: coldstart-node810-hourly
          enabled: false
      - schedule: 
          rate: rate(1 minute)
          name: warmstart-node810-minute
          enabled: false    
  awspython3:
    runtime: python3.6
    handler: aws-service-python3/handler.awsemptypython3
    events:
      - schedule: 
          rate: rate(1 hour)
          name: coldstart-python3-hourly
          enabled: false
      - schedule: 
          rate: rate(1 minute)
          name: warmstart-python3-minute
          enabled: false
  awspython36-coldstart:
    runtime: python3.7
    handler: aws-burst-invoker/handler.burst_invoker
    events:
      - schedule: 
          rate: rate(1 hour)
          name: coldstart-python3-hourly-burst
          enabled: false
          input:
            invokeCount: 2
            targetFunctionName: aws-empty-test-functions-dev-awspython3


