# Config file for aws empty-test functions - all runtimes
#
service: aws-empty-test-functions

provider:
  name: aws
  memorySize: 128
  timeout: 6
  stage: ${opt:stage,'dev'}
  region: ${opt:region,'us-east-1'}
  versionFunctions: true # Optional function versioning
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:${self:provider.region}:*:function:aws-empty-test*" 

custom:
  # you can use rate() or cron() syntax
  coldStartInterval: rate(60 minutes) # minutes => 1 hour 
  coldStartBatchSize: 3 # e.g. if 3 every 60 minutes => 3 per hour
  coldStartBatchMemory: 512
  warmStartInterval: cron(56/1 * * * ? *) # every 1 minute starting at 56 past the hour => 4 per hour (but 1st will likely be cold)

# package (e.g. .net zip) is specified per function rather than centrally as some don't need a package
package:
  individually: true 

# function parameters declared for re-use
dotnet21-param-reuse: &dotnet21-param
  runtime: dotnetcore2.1
  handler: CsharpHandlers::ServerlessPerformanceFramework.Handler::EmptyTestDotNetCore2
  package:
    artifact: aws-service-dotnetcore2/bin/release/netcoreapp2.1/deploy-package.zip

java8-param-reuse: &java8-param
  runtime: java8
  handler: com.learnspree.EmptyJava8Handler
  package:
    artifact: aws-service-java8/target/awsjava8empty-${self:provider.stage}.jar

go1x-param-reuse: &go1x-param
  runtime: go1.x
  handler: aws-service-go/bin/go-empty-function
  package:
    exclude:
      - ./aws-service-go/**
    include:
      - ./aws-service-go/bin/**

coldstart-param-reuse: &coldstart-param
  runtime: python3.7
  handler: aws-burst-invoker/handler.burst_invoker
  memorySize: ${self:custom.coldStartBatchMemory}

# individual function definitions
functions:
  # begin warm-start test functions
  aws-warm-empty-dotnet21:
    <<: *dotnet21-param
    events:
    - schedule: 
        rate: ${self:custom.warmStartInterval}
        name: warmstart-dotnet21-${self:provider.stage}-minute
        enabled: false      
  aws-warm-256-empty-dotnet21:
    <<: *dotnet21-param
    memorySize: 256
    events:
    - schedule: 
        rate: ${self:custom.warmStartInterval}
        name: warmstart-256-dotnet21-${self:provider.stage}-minute
        enabled: false
  aws-warm-512-empty-dotnet21:
    <<: *dotnet21-param
    memorySize: 512
    events:
    - schedule: 
        rate: ${self:custom.warmStartInterval}
        name: warmstart-512-dotnet21-${self:provider.stage}-minute
        enabled: false

  aws-warm-empty-go:
    <<: *go1x-param
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-go-${self:provider.stage}-minute
          enabled: false
  aws-warm-256-empty-go:
    <<: *go1x-param
    memorySize: 256
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-256-go-${self:provider.stage}-minute
          enabled: false          
  aws-warm-512-empty-go:
    <<: *go1x-param
    memorySize: 512
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-512-go-${self:provider.stage}-minute
          enabled: false 

  aws-warm-empty-java8:
    <<: *java8-param
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-java8-${self:provider.stage}-minute
          enabled: false
  aws-warm-256-empty-java8:
    <<: *java8-param
    memorySize: 256
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-256-java8-${self:provider.stage}-minute
          enabled: false          
  aws-warm-512-empty-java8:
    <<: *java8-param
    memorySize: 512
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-512-java8-${self:provider.stage}-minute
          enabled: false   

  aws-warm-empty-nodejs12x:
    runtime: nodejs12.x
    handler: aws-service-nodejs/handler.emptytestnodejs
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-nodejs12x-${self:provider.stage}-minute
          enabled: false   
  aws-warm-256-empty-nodejs12x:
    runtime: nodejs12.x
    handler: aws-service-nodejs/handler.emptytestnodejs
    memorySize: 256
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-256-nodejs12x-${self:provider.stage}-minute
          enabled: false
  aws-warm-512-empty-nodejs12x:
    runtime: nodejs12.x
    handler: aws-service-nodejs/handler.emptytestnodejs
    memorySize: 512
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-512-nodejs12x-${self:provider.stage}-minute
          enabled: false                     

  aws-warm-empty-python36:
    runtime: python3.6
    handler: aws-service-python/handler.awsemptypython
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-python36-${self:provider.stage}-minute
          enabled: false
  aws-warm-256-empty-python36:
    runtime: python3.6
    handler: aws-service-python/handler.awsemptypython
    memorySize: 256
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-256-python36-${self:provider.stage}-minute
          enabled: false          
  aws-warm-512-empty-python36:
    runtime: python3.6
    handler: aws-service-python/handler.awsemptypython
    memorySize: 512
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-512-python36-${self:provider.stage}-minute
          enabled: false 

  # begin cold-start test functions. No events - they're triggered by the batch cold start schedulers below.      
  aws-cold-empty-dotnet21:
    <<: *dotnet21-param
  aws-cold-256-empty-dotnet21:
    <<: *dotnet21-param
    memorySize: 256
  aws-cold-512-empty-dotnet21:
    <<: *dotnet21-param
    memorySize: 512

  aws-cold-empty-go:
    <<: *go1x-param
  aws-cold-256-empty-go:
    <<: *go1x-param
    memorySize: 256
  aws-cold-512-empty-go:
    <<: *go1x-param
    memorySize: 512

  aws-cold-empty-java8:
    <<: *java8-param
  aws-cold-256-empty-java8:
    <<: *java8-param
    memorySize: 256
  aws-cold-512-empty-java8:
    <<: *java8-param
    memorySize: 512

  aws-cold-empty-nodejs12x:
    runtime: nodejs12.x
    handler: aws-service-nodejs/handler.emptytestnodejs
  aws-cold-256-empty-nodejs12x:
    runtime: nodejs12.x
    handler: aws-service-nodejs/handler.emptytestnodejs
    memorySize: 256
  aws-cold-512-empty-nodejs12x:
    runtime: nodejs12.x
    handler: aws-service-nodejs/handler.emptytestnodejs
    memorySize: 512

  aws-cold-empty-python36:
    runtime: python3.6
    handler: aws-service-python/handler.awsemptypython
  aws-cold-256-empty-python36:
    runtime: python3.6
    handler: aws-service-python/handler.awsemptypython
    memorySize: 256
  aws-cold-512-empty-python36:
    runtime: python3.6
    handler: aws-service-python/handler.awsemptypython
    memorySize: 512

  # begin cold-start-scheduler functions
  awspython36-coldstart:
    <<: *coldstart-param
    events:
      - schedule: 
          rate: ${self:custom.coldStartInterval}
          name: coldstart-python36-${self:provider.stage}-hourly-burst
          enabled: false
          input:
            invokeCount: ${self:custom.coldStartBatchSize}
            targetFunctionName: 
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-python36
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-256-empty-python36
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-512-empty-python36

  awsnodejs12x-coldstart:
    <<: *coldstart-param
    events:
      - schedule: 
          rate: ${self:custom.coldStartInterval}
          name: coldstart-nodejs12x-${self:provider.stage}-hourly-burst
          enabled: false
          input:
            invokeCount: ${self:custom.coldStartBatchSize}
            targetFunctionName: 
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-nodejs12x
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-256-empty-nodejs12x
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-512-empty-nodejs12x

  awsjava8-coldstart:
    <<: *coldstart-param
    events:
      - schedule: 
          rate: ${self:custom.coldStartInterval}
          name: coldstart-java8-${self:provider.stage}-hourly-burst
          enabled: false
          input:
            invokeCount: ${self:custom.coldStartBatchSize}
            targetFunctionName: 
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-java8
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-256-empty-java8
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-512-empty-java8

  awsgo-coldstart:
    <<: *coldstart-param
    events:
      - schedule: 
          rate: ${self:custom.coldStartInterval}
          name: coldstart-go-${self:provider.stage}-hourly-burst
          enabled: false
          input:
            invokeCount: ${self:custom.coldStartBatchSize}
            targetFunctionName: 
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-go
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-256-empty-go
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-512-empty-go

  awsdotnet2-coldstart:
    <<: *coldstart-param
    events:
      - schedule: 
          rate: ${self:custom.coldStartInterval}
          name: coldstart-dotnet21-${self:provider.stage}-hourly-burst
          enabled: false
          input:
            invokeCount: ${self:custom.coldStartBatchSize}
            targetFunctionName: 
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-dotnet21
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-256-empty-dotnet21
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-512-empty-dotnet21

