# Config file for aws empty-test functions - all runtimes
#
service: aws-empty-test-functions

provider:
  name: aws
  memorySize: 128
  timeout: 6
  stage: ${opt:stage,'dev'}
  region: ${opt:region,'us-east-1'}
  versionFunctions: true # Optional function versioning
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:${self:provider.region}:*:function:aws-empty-test*" 

custom:
  # you can use rate() or cron() syntax
  coldStartInterval: rate(60 minutes) # minutes => 1 hour 
  coldStartBatchSize: 3 # e.g. => 6 every 60 minutes => 6 per hour
  coldStartBatchMemory: 512
  warmStartInterval: cron(56/1 * * * ? *) # every 1 minute starting at 56 past the hour => 4 per hour (but 1st will likely be cold)

# package (e.g. .net zip) is specified per function rather than centrally as some don't need a package
package:
  individually: true 

# individual function definitions
functions:
  # begin warm-start test functions
  aws-warm-empty-dotnet21:
    runtime: dotnetcore2.1
    handler: CsharpHandlers::ServerlessPerformanceFramework.Handler::EmptyTestDotNetCore2
    package:
      artifact: aws-service-dotnetcore2/bin/release/netcoreapp2.1/deploy-package.zip
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-dotnet21-${self:provider.stage}-minute
          enabled: false
  aws-warm-empty-go:
    runtime: go1.x
    handler: aws-service-go/bin/go-empty-function
    package:
      exclude:
        - ./aws-service-go/**
      include:
        - ./aws-service-go/bin/**
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-go-${self:provider.stage}-minute
          enabled: false
  aws-warm-empty-java8:
    runtime: java8
    handler: com.learnspree.EmptyJava8Handler
    package:
      artifact: aws-service-java8/target/awsjava8empty-${self:provider.stage}.jar
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-java8-${self:provider.stage}-minute
          enabled: false
  aws-warm-empty-nodejs12x:
    runtime: nodejs12.x
    handler: aws-service-nodejs12x/handler.emptytestnodejs12x
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-nodejs12x-${self:provider.stage}-minute
          enabled: false    
  aws-warm-empty-python36:
    runtime: python3.6
    handler: aws-service-6/handler.awsemptypython3
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-python36-${self:provider.stage}-minute
          enabled: false
  # begin cold-start test functions. No events - they're triggered by the batch cold start schedulers below.      
  aws-cold-empty-dotnet21:
    runtime: dotnetcore2.1
    handler: CsharpHandlers::ServerlessPerformanceFramework.Handler::EmptyTestDotNetCore2
    package:
      artifact: aws-service-dotnetcore2/bin/release/netcoreapp2.1/deploy-package.zip
  aws-cold-empty-go:
    runtime: go1.x
    handler: aws-service-go/bin/go-empty-function
    package:
      exclude:
        - ./aws-service-go/**
      include:
        - ./aws-service-go/bin/**
  aws-cold-empty-java8:
    runtime: java8
    handler: com.learnspree.EmptyJava8Handler
    package:
      artifact: aws-service-java8/target/awsjava8empty-${self:provider.stage}.jar
  aws-cold-empty-nodejs12x:
    runtime: nodejs12.x
    handler: aws-service-nodejs12x/handler.emptytestnodejs12x
  aws-cold-empty-python36:
    runtime: python3.6
    handler: aws-service-python36/handler.awsemptypython36
  # begin cold-start-scheduler functions
  awspython36-coldstart:
    runtime: python3.7
    handler: aws-burst-invoker/handler.burst_invoker
    memorySize: ${self:custom.coldStartBatchMemory}
    events:
      - schedule: 
          rate: ${self:custom.coldStartInterval}
          name: coldstart-python36-${self:provider.stage}-hourly-burst
          enabled: false
          input:
            invokeCount: ${self:custom.coldStartBatchSize}
            targetFunctionName: aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-python36
  awsnodejs12x-coldstart:
    runtime: python3.7
    handler: aws-burst-invoker/handler.burst_invoker
    memorySize: ${self:custom.coldStartBatchMemory}
    events:
      - schedule: 
          rate: ${self:custom.coldStartInterval}
          name: coldstart-nodejs12x-${self:provider.stage}-hourly-burst
          enabled: false
          input:
            invokeCount: ${self:custom.coldStartBatchSize}
            targetFunctionName: aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-nodejs12x
  awsjava8-coldstart:
    runtime: python3.7
    handler: aws-burst-invoker/handler.burst_invoker
    memorySize: ${self:custom.coldStartBatchMemory}
    events:
      - schedule: 
          rate: ${self:custom.coldStartInterval}
          name: coldstart-java8-${self:provider.stage}-hourly-burst
          enabled: false
          input:
            invokeCount: ${self:custom.coldStartBatchSize}
            targetFunctionName: aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-java8
  awsgo-coldstart:
      runtime: python3.7
      handler: aws-burst-invoker/handler.burst_invoker
      memorySize: ${self:custom.coldStartBatchMemory}
      events:
        - schedule: 
            rate: ${self:custom.coldStartInterval}
            name: coldstart-go-${self:provider.stage}-hourly-burst
            enabled: false
            input:
              invokeCount: ${self:custom.coldStartBatchSize}
              targetFunctionName: aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-go
  awsdotnet2-coldstart:
        runtime: python3.7
        handler: aws-burst-invoker/handler.burst_invoker
        memorySize: ${self:custom.coldStartBatchMemory}
        events:
          - schedule: 
              rate: ${self:custom.coldStartInterval}
              name: coldstart-dotnet21-${self:provider.stage}-hourly-burst
              enabled: false
              input:
                invokeCount: ${self:custom.coldStartBatchSize}
                targetFunctionName: aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-dotnet21


