# Serverless Performance Test Framework
# Empty Function - AWS Node 8.10
service: awsservicenode810

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128


functions:
  awsnode810:
    handler: handler.emptytestnode810
    events:
      - schedule: 
          rate: rate(1 hour)
          name: coldstart-node810-hourly
          enabled: false
      - schedule: 
          rate: rate(1 minute)
          name: warmstart-node810-minute
          enabled: false


