# Config file for aws empty-test functions
#
service: aws-empty-test-functions-go

provider:
  name: aws
  memorySize: 128
  timeout: 6
  stage: ${opt:stage,'dev'}
  region: ${opt:region,'us-east-1'}
  versionFunctions: true # Optional function versioning

custom:
  warmStartInterval: cron(0-15 0/4 * * ? *) # every 4 hours we do a 15-minute series starting at 0 past the hour => 15 per hour, 6 times a day

# package (e.g. .net zip) is specified per function rather than centrally as some don't need a package
package:
  individually: true 

go1x-param-reuse: &go1x-param
  runtime: go1.x
  handler: bin/go-empty-function
  package:
    exclude:
      - ./aws-service-go/**
    include:
      - ./aws-service-go/bin/**

# individual function definitions
functions:
  # begin warm-start test functions
  aws-warm-empty-go:
    <<: *go1x-param
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-go-${self:provider.stage}-minute
          enabled: false
  aws-warm-256-empty-go:
    <<: *go1x-param
    memorySize: 256
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-256-go-${self:provider.stage}-minute
          enabled: false          
  aws-warm-512-empty-go:
    <<: *go1x-param
    memorySize: 512
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-512-go-${self:provider.stage}-minute
          enabled: false 

  # begin cold-start test functions. 
  # No events - they're triggered by the batch cold start schedulers below.      
  aws-cold-empty-go:
    <<: *go1x-param
  aws-cold-256-empty-go:
    <<: *go1x-param
    memorySize: 256
  aws-cold-512-empty-go:
    <<: *go1x-param
    memorySize: 512

