# Serverless Performance Test Framework
# Empty Function - AWS Node 6.10
service: awsservicenode610

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128


functions:
  awsnode610:
    handler: handler.emptytestnode610

# Sample event schedule below but commenting this out
# as various schedules will be needed depending on the test scenario
# e.g. spread out for cold-start test or all together for warm-start.
# Example below triggers the function 3 times (that's why there's 3 separate schedules)
# each at one-minute intervals - i.e. 3 times every minute.
# NOTE - to get executions at EXACTLY the same moment, a cron() type expression might be better.
# See https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#CronExpressions
#    events:
#      - schedule: 
#          rate: rate(1 minute)
#          name: instance-one
#          enabled: false
#      - schedule: 
#          rate: rate(1 minute)
#          name: instance-two
#          enabled: false
#      - schedule: 
#          rate: rate(1 minute)
#          name: instance-three
#          enabled: false

