# Config file for aws empty-test functions 
#
service: aws-empty-test-functions-python

provider:
  name: aws
  memorySize: 128
  timeout: 6
  stage: ${opt:stage,'dev'}
  region: ${opt:region,'us-east-1'}
  versionFunctions: true # Optional function versioning
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:${self:provider.region}:*:function:aws-empty-test*" 

custom:
  # you can use rate() or cron() syntax
  coldStartInterval: rate(60 minutes) # minutes => 1 hour 
  coldStartBatchSize: 3 # e.g. if 3 every 60 minutes => 3 per hour
  coldStartBatchMemory: 512
  warmStartInterval: cron(56/1 * * * ? *) # every 1 minute starting at 56 past the hour => 4 per hour (but 1st will likely be cold)

# function parameters declared for re-use
coldstart-param-reuse: &coldstart-param
  runtime: python3.8
  handler: ../aws-burst-invoker/handler.burst_invoker
  memorySize: ${self:custom.coldStartBatchMemory}

# individual function definitions
functions:
  aws-warm-empty-python36:
    runtime: python3.6
    handler: handler.awsemptypython
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-python36-${self:provider.stage}-minute
          enabled: false
  aws-warm-256-empty-python36:
    runtime: python3.6
    handler: handler.awsemptypython
    memorySize: 256
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-256-python36-${self:provider.stage}-minute
          enabled: false          
  aws-warm-512-empty-python36:
    runtime: python3.6
    handler: handler.awsemptypython
    memorySize: 512
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-512-python36-${self:provider.stage}-minute
          enabled: false 

  aws-warm-empty-python38:
    runtime: python3.8
    handler: handler.awsemptypython
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-python38-${self:provider.stage}-minute
          enabled: false
  aws-warm-256-empty-python38:
    runtime: python3.8
    handler: handler.awsemptypython
    memorySize: 256
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-256-python38-${self:provider.stage}-minute
          enabled: false          
  aws-warm-512-empty-python38:
    runtime: python3.8
    handler: handler.awsemptypython
    memorySize: 512
    events:
      - schedule: 
          rate: ${self:custom.warmStartInterval}
          name: warmstart-512-python38-${self:provider.stage}-minute
          enabled: false           

  # begin cold-start test functions. No events - they're triggered by the batch cold start schedulers below.      
  aws-cold-empty-python36:
    runtime: python3.6
    handler: handler.awsemptypython
  aws-cold-256-empty-python36:
    runtime: python3.6
    handler: handler.awsemptypython
    memorySize: 256
  aws-cold-512-empty-python36:
    runtime: python3.6
    handler: handler.awsemptypython
    memorySize: 512

  aws-cold-empty-python38:
    runtime: python3.8
    handler: handler.awsemptypython
  aws-cold-256-empty-python38:
    runtime: python3.8
    handler: handler.awsemptypython
    memorySize: 256
  aws-cold-512-empty-python38:
    runtime: python3.8
    handler: handler.awsemptypython
    memorySize: 512    

  # begin cold-start-scheduler functions
  awspython36-coldstart:
    <<: *coldstart-param
    events:
      - schedule: 
          rate: ${self:custom.coldStartInterval}
          name: coldstart-python36-${self:provider.stage}-hourly-burst
          enabled: false
          input:
            invokeCount: ${self:custom.coldStartBatchSize}
            targetFunctionName: 
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-python36
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-256-empty-python36
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-512-empty-python36

  awspython38-coldstart:
    <<: *coldstart-param
    events:
      - schedule: 
          rate: ${self:custom.coldStartInterval}
          name: coldstart-python38-${self:provider.stage}-hourly-burst
          enabled: false
          input:
            invokeCount: ${self:custom.coldStartBatchSize}
            targetFunctionName: 
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-empty-python38
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-256-empty-python38
              - aws-empty-test-functions-${self:provider.stage}-aws-cold-512-empty-python38            
